// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    double numOfArgs= Double.parseDouble(args[0]); 
		double smallHalf = 0;
		double bigHalf = 0;
		int i = 0;
		double sum = 0;
		for (i = 0 ; i <numOfArgs; i++) {	
			double random = Math.random();
			sum = sum + random;
			if(random > 0.5){
				bigHalf = bigHalf + 1;
			}else{
					smallHalf = smallHalf + 1;
				}
			}
		double finalSum = (bigHalf / smallHalf);
		System.out.println("> 0.5: "+bigHalf +" times");
		System.out.println("<= 0.5: "+smallHalf +" times");	
		System.out.println("ratio: "+finalSum);		
	}
}
//done